base: &base
  adapter: mysql2
  charset: utf8mb4
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: <%= Settings.db.default.username %>
  password: <%= Settings.db.default.password %>

default: &default
  <<: *base
  host: <%= Settings.db.default.host %>
  port: <%= Settings.db.default.port %>

master_slave: &master_slave
  <<: *default
  adapter: mysql2

development:
  <<: *default
  database: rails_sns_development

test:
  <<: *default
  database: rails_sns_test

staging:
  <<: *master_slave
  database: rails_sns_staging

production:
  <<: *master_slave
  pool: 25
  database: rails_sns_production
